yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'), ]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path
from . import views


app_name = 'users'
password_change = 'users/password_change.html'
password_change_ok = 'users/password_change_done.html'
password_reset_fm = 'users/password_reset_form.html'
password_reset_ok = 'users/password_reset_done.html'
password_reset_conf = 'users/password_reset_confirm.html'
password_reset_com = 'users/password_reset_complite.html'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name=password_change),
        name='password_change'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name=password_change_ok),
        name='password_change_done'),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name=password_reset_fm),
        name='password_reset_form'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name=password_reset_ok),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name=password_reset_conf),
        name='password_reset_confirm'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name=password_reset_com),
        name='password_reset_complete'), ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')), ]

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube</a>
    </a>
    <ul class="nav nav-pills">

      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      {% endwith %} 

      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% endwith %} 

      {% if request.user.is_authenticated %}

      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link" href="/create">Новая запись</a>
      </li>
      {% endwith %} 
      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
      </li>
      {% endwith %} 
      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      {% endwith %} 
      
      {% with request.resolver_match.view_name as view_name %} 
      <li>
        Пользователь: {{ user.username }}
      <li>
        {% endwith %} 

      {% else %}

      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
      </li>
      {% endwith %} 
      {% with request.resolver_match.view_name as view_name %} 
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endwith %} 

      {% endif %}
    </ul>

  </div>
</nav>