yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'), ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')), ]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/posts/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse
from .models import Post, Group
from django.contrib.auth import get_user_model
from .forms import PostForm


LIMIT_POST = 10
User = get_user_model()


def index(request):
    posts = Post.objects.all()
    post_list = Post.objects.order_by('-pub_date')
    paginator = Paginator(post_list, LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(posts, LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    paginator = Paginator(posts, LIMIT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_count = posts.count()
    context = {
        'post_count': post_count,
        'posts': posts,
        'author': author,
        'page_obj': page_obj
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    user = get_object_or_404(User, username=post.author)
    post_number = Post.objects.filter(author=user).count()
    context = {
        'post': post,
        'post_number': post_number
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    user = request.user
    groups = Group.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = user
            post.save()
            return redirect(reverse('posts:profile',
                                    kwargs={'username': user.username}))
    context = {
        'form': PostForm(),
        'groups': groups,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    user = request.user
    groups = Group.objects.all()
    post = Post.objects.get(id=post_id)
    if user != post.author:
        raise HttpResponseNotFound("У вас нет такого поста")
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post.id)
    form = PostForm(instance=post)
    context = {
        'form': form,
        'groups': groups,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
        {% if is_edit %}
        Редактировать запись
        {% else %}
        Добавить запись
        {% endif %}
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста
                <span class="required text-danger" >*</span>
              </label>
              <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                  {% if form.text.value %}
                  {{ form.text.value }}
                  {% endif %}
              </textarea>
              <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группы
              </label>
              <select name="group" class="form-control" id="id_group">
                <option value="">Список групп</option>
                {% for group in groups %}
                  <option
                  {% if group.id == form.group.value %}
                     selected
                  {% endif %}
                  value="{{ group.id }}">Группа: {{ group.title }}
                  </option>
                {% endfor %}
              </select>
              <small id="id_group-help" class="form-text text-muted">
                Группа, к которой будет относиться пост
              </small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
      {% endblock %}
      

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{group.title}} {% endblock %} 
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>
  <article>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>     
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  </article>
</div>  
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %} 
{% block content %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
  <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
        {% if post %}
          <a href="{% url 'posts:post_detail' post.id %}">
           подробная информация
          </a>
        {% endif %}
  </article>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
    </a>
    {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
</div>
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text |truncatewords:30 }}{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
                Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span>{{ post_number }}</span>
            </li>
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text }}
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Все посты пользователя {{ author.username }} </h1>
  <h3>Всего постов: {{ post_count }} </h3>
  <article>
    <ul>
    {% for post in page_obj %}
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>

    <p>
        {{ post.text }}
    </p>
    {% if post %}
      <a href="{% url 'posts:post_detail' post.id %}">
       подробная информация
      </a>
    {% endif %}
  </article>
{% if post.group %}
<a href="{% url 'posts:group_list' post.group.slug %}">
      все записи группы
</a>
{% endif %}
{% endfor %}
  <hr>
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}